---
title: "Python Basics"
subtitle: "-"
execute: 
  enabled: false
format:
  revealjs: 
    smaller: true
    scrollable: true
    code-block-height: 650px  
    theme: dark  
    slide-number: true
    code-fold: false
    chalkboard: 
      buttons: false
    preview-links: auto
---

# Data Arrays

A sequence is a collection of ordered objects. Ordered in the sense you can assign indexes to its elements - the first, the second and so on. Being able to store data in sequences is very useful for data science.

There are two ways you can have sequences in Python. You can use have tuple’s or list’s. The difference between the two is that tuple are frozen (you cannot change them once you make them) but you can add or remove items for list’s. Let’s look at tuples first.

## Tuples

In Python, you can create a tuple by placing comma-separated elements within parentheses.

In [1]:
#Populating a tuple with Integers
x = (1, 2, 3)
print(x)

(1, 2, 3)


You can get the first element of your tuple by using square brackets and passing the indexing. Remember that Python has an index system where the first element index is 0.

In [2]:
#Getting the first element
x[0]

1

You can populate tuples with different data types:

In [3]:
mytuple = ("vinicius", 1, 3.1415)
print(mytuple)

('vinicius', 1, 3.1415)


You cannot remove, add or modify the elements of a tuple! **Tuples are immutable objects in Python**

In [4]:
# mytuple[0] = "Bjorn"

## Lists

Lists are similar to tuples, containers of many things, but they can be modified - delete elements, add elements, change existing elements. Here is a list with different objects inside (including another list):

In [5]:
mylist = ["Vinicius", 1.0, 3.1415, ["google.com"]]
print(mylist)

['Vinicius', 1.0, 3.1415, ['google.com']]


You can also instantiate an empty list!

In [6]:
myemptylist = []
print(myemptylist)

[]


You can modify existing elements of a list.

In [7]:
mylist[0] = "Bjorn"

In [8]:
print(mylist)

['Bjorn', 1.0, 3.1415, ['google.com']]


You can count how many elements are in a list (it's the same for tuples) using the ``len`` function.

In [9]:
len(mylist)

4

You can do many things with lists. If you want to know all the things you can do with lists (and any other Python object), you can using the ``help()`` command:

In [10]:
help([mylist])

Help on list object:

class list(object)
 |  list(iterable=(), /)
 |
 |  Built-in mutable sequence.
 |
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |
 |  Methods defined here:
 |
 |  __add__(self, value, /)
 |      Return self+value.
 |
 |  __contains__(self, key, /)
 |      Return bool(key in self).
 |
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __getitem__(self, index, /)
 |      Return self[index].
 |
 |  __gt__(self, value, /)
 |      Return self>value.
 |
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  __it

let's try the ``pop`` command to remove the first element of my list.

In [11]:
mylist.pop(0)

'Bjorn'

It prints which element I removed

In [12]:
print(mylist)

[1.0, 3.1415, ['google.com']]


In [13]:
type("vene")

str

You can also iterate over the elements of a list. Let's say you want to find out if there's a string in your list. For small lists, you can look manually. However, if it's large,  you could do a for loop!


In [14]:
mysecondlist = [1, "Vinicius"]

for element in mysecondlist:
    if type(element) == str:
        print("There is a string in my list")

There is a string in my list


## Matrices

While lists and tuples are sequences and can only index their elements with a single number, we often need more complex structures, such as matrices, which require indexing with more than one number.

Lists and tuples are built-in elements of Python. To work with matrices, we need to use external numerical libraries. ``Numpy``is the recommended library for it

In [15]:
import numpy as np #Making a shorter name through "as" keyword

In [16]:
# Creating a matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])


In [17]:
# Accessing elements
print("\nElement at (0, 0):", matrix[0, 0])
print("Element at (1, 2):", matrix[1, 2])



Element at (0, 0): 1
Element at (1, 2): 6


### Slicing

You can "slice" matrix elements in very different ways in Python

In [18]:
# Basic Slicing
print("\nFirst row:", matrix[0, :])
print("Second column:", matrix[:, 1])


First row: [1 2 3]
Second column: [2 5 8]


In [19]:
# Slicing with step
print("\nEvery other element in the first row:")
every_other_element = matrix[0, 0::2]
print(every_other_element)
print("Explanation: This slices the first row to get every other element (step size of 2).")


Every other element in the first row:
[1 3]
Explanation: This slices the first row to get every other element (step size of 2).


In [20]:
# Reverse slicing
print("\nReversed rows:")
reversed_rows = matrix[-1::-1] # Starting from last element up to the first with step size 1
print(reversed_rows)
print("Explanation: This reverses the rows of the matrix.")


Reversed rows:
[[7 8 9]
 [4 5 6]
 [1 2 3]]
Explanation: This reverses the rows of the matrix.


### Operations

Matrix addition is the simplest operation you can do with two matrices.

In [21]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])


matrix2 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])

print(matrix + matrix2)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


What about summing a matrix with a vector?

In [22]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

vector = np.array([[1, 2, 3]]) #My array has one element and inside this element there are 3 other elements.

print("Matrix shape is:", matrix.shape)
print("Vector shape is:", vector.shape)

Matrix shape is: (3, 3)
Vector shape is: (1, 3)


This operation should not work, right?

In [23]:
matrix + vector

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In NumPy, broadcasting allows operations on arrays of different shapes. Broadcasting automatically expands the dimensions of the smaller array to match the larger array by repeating its elements along the mismatched dimensions, making the arrays compatible for element-wise operations.

It does the same for the ``*`` operation

In [24]:
matrix*vector

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

If you want to make sure your operations follows what you know about linear algebra regarding matrix multiplication, use the ``dot`` operation instead of ``*``.

For the ``+`` operation, there is no other way. You have to be intentional on the way you write the code.

In [25]:
# np.dot(matrix, vector) ## that fails

In [26]:
np.dot(vector, matrix) ## That works as we know from linear algebra!

array([[30, 36, 42]])

You can also apply functions to the elements of a numpy array:

In [27]:
np.tanh(vector)

array([[0.76159416, 0.96402758, 0.99505475]])

In [28]:
np.log(vector)

array([[0.        , 0.69314718, 1.09861229]])

In [29]:
np.tan(vector)

array([[ 1.55740772, -2.18503986, -0.14254654]])

<div class="alert alert-block alert-warning"><b>Attention:</b> Vector*Vector or Matrix*Matrix does not perform dot product. It squares each element of the vector or matrix! </div>

In [30]:
vector*vector #Squares each element of the vector (it's not dot product)

array([[1, 4, 9]])

In [31]:
matrix*matrix #Squares each element of the matrix

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [32]:
np.dot(matrix, matrix) #Do matrix, matrix multiplication as in Linear Algebra

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])